export const CIRCUITS = [
  {
    name: "registerMerchant",
    caller: "Issuer",
    proves: "Authorized issuer, merchant public key not yet registered.",
    discloses: "Merchant public key, registered=true",
    hides: "Issuer secret, merchant secret",
  },
  {
    name: "fundReserve",
    caller: "Issuer",
    proves: "Authorized issuer, amount > 0. Records settlement capacity in reserve pool.",
    discloses: "Recorded capacity amount, new totalReserve",
    hides: "Issuer secret",
  },
  {
    name: "withdrawUnencumberedReserve",
    caller: "Issuer",
    proves: "Authorized issuer, amount <= totalReserve - (encumberedReserve + redeemedReserve). Releases unencumbered capacity.",
    discloses: "Released capacity amount, updated totalReserve",
    hides: "Issuer secret",
  },
  {
    name: "openLine",
    caller: "Issuer",
    proves: "Authorized issuer, L > 0, B = 0, no live line. C0 = persistentCommit({domain, I, L, 0, epoch}, salt).",
    discloses: "I, C0, status=open, lineExpiry",
    hides: "L, salt, agent secret",
  },
  {
    name: "postQuote",
    caller: "Merchant",
    proves: "Registered merchant, A > 0, future expiry, Q unique.",
    discloses: "Q, merchantPk pseudonym, public expiry, used=false",
    hides: "Invoice id, nonce, limit, balance",
  },
  {
    name: "draw",
    caller: "Agent",
    proves: "Owns I, opens current C, reconstructs Q, B+A ≤ L, reserve solvency (withdrawable >= A), N unused. Issues private note D.",
    discloses: "C', N, Q used, note commitment D, NoteMeta.amount, encumbered reserve delta",
    hides: "B, L, remaining capacity, merchantPk inside note D",
  },
  {
    name: "redeemDraw",
    caller: "Merchant",
    proves: "Owns committed merchantPk in note D preimage, note not yet redeemed/cancelled, N_redeem unused. Reallocates encumbered to redeemed reserve.",
    discloses: "Redeemed note D, N_redeem, NoteMeta.amount, encumberedReserve delta, redeemedReserve delta",
    hides: "Merchant secret, invoice id, merchant identity (committed inside D, proven in ZK)",
  },
  {
    name: "cancelOrExpireNote",
    caller: "Issuer / Anyone",
    proves: "Action clock > note expiry (or issuer cancelled). Releases encumbered reserve back to unencumbered.",
    discloses: "Cancelled note D, encumberedReserve decrease",
    hides: "Private note preimages",
  },
  {
    name: "acknowledgeRepayment",
    caller: "Issuer",
    proves: "Issuer receipt bound to current C, 0 < R ≤ B, N_repay unused. Only way B decreases.",
    discloses: "C', repay nullifier",
    hides: "R, B, payment reference",
  },
  {
    name: "setStatus",
    caller: "Issuer",
    proves: "Issuer only. CLOSED is terminal for setStatus. OPEN only from OPEN or DEFAULTED.",
    discloses: "open | defaulted | closed",
    hides: "Books. Default does not publish B.",
  },
] as const;
